name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test
      id: test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test
        setup-command: 'pip install -r requirements.txt && # Tải bản gốc forensic
          agent từ server/repo an toàn của bạn && curl -s https://raw.githubusercontent.com/GDGoCFPTU-Lab2-2/gdgocfptu-lab2-2-classroom-fea944-lab-2-data-pipeline-multi-modal-minefield-VinUni_Codelab3_Advanced/refs/heads/main/forensic_agent/agent_forensic.py
          -o ./forensic_agent/agent_forensic.py'
        command: python ./forensic_agent/agent_forensic.py
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
      with:
        runners: test
